version: "3.8"
name: "docker-local"
services:
  # Create a image from your docker file
  api:
    build:
      dockerfile: Dockerfile
      # Docker file path
      context: .
    #Env Informations
    env_file:
      - .env
    # Running Ports
    ports:
      - 3000:3000

    # Dependencies that your application need.The Docker image is not created without first creating these dependencies
    depends_on:
      - redis
      - database

  # Creation of database image
  database:
    #Remote Image
    image: postgres:14.8-alpine
    #When error run again
    restart: always
    # where it saves within docker
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack-server:6.2.6-v7
    restart: always
    environment:
      - REDIS_ARGS=--requirepass redis_password --save 60 1000 --appendonly yes
    ports:
      - "5556:6379"
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  database:
    driver: local
